# Generated by Django 2.0.7 on 2018-07-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuri', '0002_auto_20180727_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='upload',
            field=models.ImageField(upload_to='restaurant-images/'),
        ),
    ]
